name: publish kgdata
on:
  push:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.8
      - name: Install Poetry
        run: pip install poetry
      - name: Install Dependencies
        run: poetry install
      - name: Publish
        run: poetry publish --build --username $PYPI_USER --password $PYPI_PWD
        env:
          PYPI_USER: __token__
          PYPI_PWD: ${{ secrets.PYPI_TOKEN }}
